#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 10 09:57:06 2022

@author: carlmagnusson
"""
# --- Day 9: Rope Bridge ---
# This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

# It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

# You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.

# Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

# Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.

# Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

# ....
# .TH.
# ....

# ....
# .H..
# ..T.
# ....

# ...
# .H. (H covers T)
# ...
# If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:

# .....    .....    .....
# .TH.. -> .T.H. -> ..TH.
# .....    .....    .....

# ...    ...    ...
# .T.    .T.    ...
# .H. -> ... -> .T.
# ...    .H.    .H.
# ...    ...    ...
# Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:

# .....    .....    .....
# .....    ..H..    ..H..
# ..H.. -> ..... -> ..T..
# .T...    .T...    .....
# .....    .....    .....

# .....    .....    .....
# .....    .....    .....
# ..H.. -> ...H. -> ..TH.
# .T...    .T...    .....
# .....    .....    .....
# You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

# For example:

# R 4
# U 4
# L 3
# D 1
# R 4
# D 1
# L 5
# R 2
# This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):

# == Initial State ==

# ......
# ......
# ......
# ......
# H.....  (H covers T, s)

# == R 4 ==

# ......
# ......
# ......
# ......
# TH....  (T covers s)

# ......
# ......
# ......
# ......
# sTH...

# ......
# ......
# ......
# ......
# s.TH..

# ......
# ......
# ......
# ......
# s..TH.

# == U 4 ==

# ......
# ......
# ......
# ....H.
# s..T..

# ......
# ......
# ....H.
# ....T.
# s.....

# ......
# ....H.
# ....T.
# ......
# s.....

# ....H.
# ....T.
# ......
# ......
# s.....

# == L 3 ==

# ...H..
# ....T.
# ......
# ......
# s.....

# ..HT..
# ......
# ......
# ......
# s.....

# .HT...
# ......
# ......
# ......
# s.....

# == D 1 ==

# ..T...
# .H....
# ......
# ......
# s.....

# == R 4 ==

# ..T...
# ..H...
# ......
# ......
# s.....

# ..T...
# ...H..
# ......
# ......
# s.....

# ......
# ...TH.
# ......
# ......
# s.....

# ......
# ....TH
# ......
# ......
# s.....

# == D 1 ==

# ......
# ....T.
# .....H
# ......
# s.....

# == L 5 ==

# ......
# ....T.
# ....H.
# ......
# s.....

# ......
# ....T.
# ...H..
# ......
# s.....

# ......
# ......
# ..HT..
# ......
# s.....

# ......
# ......
# .HT...
# ......
# s.....

# ......
# ......
# HT....
# ......
# s.....

# == R 2 ==

# ......
# ......
# .H....  (H covers T)
# ......
# s.....

# ......
# ......
# .TH...
# ......
# s.....
# After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

# ..##..
# ...##.
# .####.
# ....#.
# s###..
# So, there are 13 positions the tail visited at least once.

# Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?



import numpy as np 

#funktion som kollar om huvud och svans är grannar
def IsNeighbour(HCP, TCP): 
    rowdiff = HCP[0] - TCP[0]
    coldiff = HCP[1] - TCP[1] 
    
    if abs(rowdiff) <= 1 and abs(coldiff) == 0: 
        return 1
    elif abs(coldiff) <= 1 and abs(rowdiff) == 0: 
        return 1
    elif abs(rowdiff) == 1 and abs(coldiff) == 1:
        return 1
    elif abs(rowdiff) == 0 and abs(coldiff) == 0:
        return 1
    else: 
        return 0

#Funktion som flyttar svansen så att det är fortsatt granne med huvudet
def movetail(HCP, TCP, direction): 
    
    rowdiff = HCP[0] - TCP[0]
    coldiff = HCP[1] - TCP[1] 
    
    TailNewPosition = []
    #Om diagonal i y-led
    if abs(rowdiff) == 2 and abs(coldiff) == 1: 
        if direction == 'U': 
            TailNewPosition = [TCP[0] + 1, TCP [1] + coldiff]
        elif direction == 'D': 
            TailNewPosition = [TCP[0] - 1, TCP [1] + coldiff]
        tail.append(TailNewPosition)
    #Om diagonal i x-led
    elif abs(rowdiff) == 1 and abs(coldiff) == 2: 
        if direction == 'R': 
            TailNewPosition = [TCP[0] + rowdiff, TCP[1] + 1]
        elif direction == 'L':
            TailNewPosition = [TCP[0] + rowdiff, TCP[1] - 1]
        tail.append(TailNewPosition)
    # Om vertikal förflyttning 
    elif abs(rowdiff) == 2 and abs(coldiff) == 0: 
        if direction == 'U': 
            TailNewPosition = [TCP[0] + 1, TCP[1]]
        elif direction == 'D': 
            TailNewPosition = [TCP[0] - 1, TCP[1]]
        tail.append(TailNewPosition)
    # Om horisontell förflyttning
    elif abs(rowdiff) == 0 and abs(coldiff) == 2: 
        if direction == 'R': 
            TailNewPosition = [TCP[0], TCP[1] + 1]
        elif direction == 'L': 
            TailNewPosition = [TCP[0], TCP[1] - 1]
        tail.append(TailNewPosition)
        
    return
        
#Funktion som förflyttar huvudet.   
def movehead(head, tail, r, txt): 
    #Riktning och steg plockas ut ur textsträngen. 
    direction = txt[0]
    steps = int(txt[2:])
 
    #Flyttar huvudet 1 steg åt gången, itererar över antal steg som ska tas. 
    # Efter varje iteration kollar vi om svansen måste flyttas också 
    for i in range(1, steps + 1):
        if direction == 'R': 
            head.append([head[r][0], head[r][1] + i])
        elif direction == 'L': 
             head.append([head[r][0], head[r][1] - i])
        elif direction == 'U': 
             head.append([head[r][0] + i, head[r][1]])
        elif direction == 'D': 
            head.append([head[r][0] - i, head[r][1]])
        
        Head_current_position = head[len(head)-1]
        Tail_current_position = tail[len(tail)-1]
        
        #Om svans och huvud inte längre är grannar, flytta svansen. 
        if IsNeighbour(Head_current_position, Tail_current_position) == 0: 
            movetail(Head_current_position, Tail_current_position, direction)
            
        

    return

#Börjar med att bara läsa in dokumentet 
with open('day9.txt') as f: 
    #Startpunkter för huvud och svans. 
    head = [[0, 0]] 
    tail = [[0, 0]]
    
    #Ska hålla vår input
    movements = []
    
    for line in f: 
        movements.append(line.rstrip())

#Loopar över movements och flyttar huvud och svans vid behov. 
for r in range(0, len(movements)): 
    size = len(head) - 1
    movehead(head, tail, size, movements[r])

#Lite manipulation för att bli av med dubletter. 
tail = set(tuple(element) for element in tail)
tail = list(dict.fromkeys(tail))

#resultat
print('Result 1: ' + str(len(tail)))

